from .activity import setup_activity_page
from .add import setup_add_page
from .backup_manager import setup_backup_manager_page
from .backup_restore import setup_backup_restore_page
from .home import setup_home_page
from .import_export import setup_import_export_page
from .manage import setup_manage_installments_page
from .send_notification import setup_send_notification_page
from .view import setup_view_page
from .financial_dashboard import setup_financial_dashboard_page
from .expenses import setup_expenses_page
from .contracts import setup_contracts_page
from .tasks_page import setup_tasks_page
from .documents_page import setup_documents_page
